max_stack: 1Mb
max_data: 10GB
#max_time: 2s
mount_namespace: false
user_namespace: false
mount_root: false

fs:
# - path: /home
#   action: deny
  - path: /tmp
    action: readonly
  - path: /
    action: allow
