name: auto-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Compile
        run: |
          sudo apt-get update
          sudo apt-get install -y libcap-dev
          rm -rf build
          mkdir build
          cd build

          cmake ..
          make
          cd ..
        env:
          CC:   gcc-10
          CXX:  g++-10
      - name: Run tests
        run: ./test/test_all.sh
        env:
          CC: gcc-10
          CXX: g++-10
